# https://taskfile.dev
version: '3'

dotenv: [.env]

env:
#  PUBLIC_POCKETBASE_URL: http://localhost:8090
#  POCKETBASE_URL: http://localhost:8090

tasks:
  default:
    deps: [pb, dev]
    cmds:
      # - task: dev
      # - task: pb

  dev:
    cmds:
      - npm run dev

  build:
    cmds:
      - npm run build

  docker:
    # deps: [build]
    cmds:
      - docker compose up --build -d

  docker-dev:
    cmd: docker compose -f docker-compose.dev.yml up

  docker-build:
    # deps: [build]
    cmds:
      - docker compose build

  docker-deploy:
    cmds:
      - cmd: git stash -u -m "task docker-deploy"
        ignore_error: true
      - git pull
      - task: docker

  deploy:
    desc: Run deployment from global Taskfile
    cmds:
      - task skillshelf -g

  pb:
    dir: pocketbase
    cmd: ./pocketbase serve

  types:
    cmd: npx pocketbase-typegen --db ./pocketbase/pb_data/data.db --out ./src/lib/pocketbase-types.ts

  npm-install:
    cmds:
      - npm i
      - cp .env.example .env

  pb-download:
    dir: pocketbase
    cmds:
      - cmd: wget https://cdn.danzl.it/apps/pocketbase.exe
        platforms: [windows]

  install:
    deps: [npm-install, pb-download]

  example:
    aliases:
      - seed
      - testdata
    cmd: node pocketbase/seed-en.mjs
